-- CreateTable
CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'RECRUITER', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "SearchRun" ("id" TEXT NOT NULL PRIMARY KEY, "country" TEXT NOT NULL, "destination" TEXT NOT NULL, "position" TEXT NOT NULL, "language" TEXT NOT NULL, "dateRange" TEXT NOT NULL, "generatedQueries" TEXT NOT NULL, "resultsFound" INTEGER NOT NULL DEFAULT 0, "qualifiedResults" INTEGER NOT NULL DEFAULT 0, "createdById" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SearchRun_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id"));
CREATE TABLE "Lead" ("id" TEXT NOT NULL PRIMARY KEY, "publicDisplayName" TEXT NOT NULL, "sourceName" TEXT NOT NULL, "sourceUrl" TEXT NOT NULL, "sourcePostTitle" TEXT NOT NULL, "sourcePostExcerpt" TEXT NOT NULL, "sourcePublishedAt" DATETIME NOT NULL, "detectedCountry" TEXT, "detectedDestination" TEXT, "detectedExperience" TEXT, "detectedSkills" TEXT NOT NULL DEFAULT '[]', "detectedLanguage" TEXT, "classification" TEXT NOT NULL, "explicitJobIntent" BOOLEAN NOT NULL DEFAULT false, "confidenceScore" INTEGER NOT NULL, "aiSummary" TEXT NOT NULL, "riskFlags" TEXT NOT NULL DEFAULT '[]', "status" TEXT NOT NULL DEFAULT 'PENDING_REVIEW', "assignedRecruiterId" TEXT, "searchRunId" TEXT, "registrationToken" TEXT NOT NULL, "consentToContinue" BOOLEAN NOT NULL DEFAULT false, "doNotContact" BOOLEAN NOT NULL DEFAULT false, "possibleDuplicateId" TEXT, "internalNote" TEXT, "discoveredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewedAt" DATETIME, "contactedAt" DATETIME, "registeredAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Lead_assignedRecruiterId_fkey" FOREIGN KEY ("assignedRecruiterId") REFERENCES "User" ("id"), CONSTRAINT "Lead_searchRunId_fkey" FOREIGN KEY ("searchRunId") REFERENCES "SearchRun" ("id"));
CREATE UNIQUE INDEX "Lead_sourceUrl_key" ON "Lead"("sourceUrl"); CREATE UNIQUE INDEX "Lead_registrationToken_key" ON "Lead"("registrationToken");
CREATE TABLE "OutreachMessage" ("id" TEXT NOT NULL PRIMARY KEY, "leadId" TEXT NOT NULL, "messageText" TEXT NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "approved" BOOLEAN NOT NULL DEFAULT false, "approvedBy" TEXT, "simulatedResponse" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "OutreachMessage_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead" ("id") ON DELETE CASCADE);
CREATE TABLE "ScreeningSession" ("id" TEXT NOT NULL PRIMARY KEY, "leadId" TEXT NOT NULL, "preferredLanguage" TEXT NOT NULL DEFAULT 'English', "currentQuestion" INTEGER NOT NULL DEFAULT 0, "completed" BOOLEAN NOT NULL DEFAULT false, "pausedForHuman" BOOLEAN NOT NULL DEFAULT false, "summary" TEXT, "recommendedNextStep" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME, CONSTRAINT "ScreeningSession_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead" ("id") ON DELETE CASCADE);
CREATE TABLE "ScreeningAnswer" ("id" TEXT NOT NULL PRIMARY KEY, "screeningSessionId" TEXT NOT NULL, "questionKey" TEXT NOT NULL, "questionText" TEXT NOT NULL, "answerText" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ScreeningAnswer_screeningSessionId_fkey" FOREIGN KEY ("screeningSessionId") REFERENCES "ScreeningSession" ("id") ON DELETE CASCADE);
CREATE TABLE "TestApplication" ("id" TEXT NOT NULL PRIMARY KEY, "leadId" TEXT NOT NULL, "fullName" TEXT NOT NULL, "country" TEXT NOT NULL, "contactMethod" TEXT NOT NULL, "contactValue" TEXT NOT NULL, "experience" TEXT NOT NULL, "overseasExperience" TEXT NOT NULL, "skills" TEXT NOT NULL, "availability" TEXT NOT NULL, "preferredLanguage" TEXT NOT NULL, "consentAccepted" BOOLEAN NOT NULL, "submittedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TestApplication_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead" ("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "TestApplication_leadId_key" ON "TestApplication"("leadId");
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT, "leadId" TEXT, "action" TEXT NOT NULL, "details" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id"), CONSTRAINT "AuditLog_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead" ("id"));
