import express from "express";
import helmet from "helmet";
import cors from "cors";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { z } from "zod";
import { createAnalyzerProvider, createSearchProvider, enforceApplicantIntent, generateSearchQueries, matchesSelectedCountry, MockAnalyzerProvider, SimulatedMessagingProvider } from "./providers.js";
import { assertTransition, screeningQuestions } from "./workflow.js";

const globalForPrisma=globalThis as unknown as {prisma?:PrismaClient};
export const prisma=globalForPrisma.prisma??new PrismaClient();
globalForPrisma.prisma=prisma;
const analyzerSelection=createAnalyzerProvider();
const searchSelection=createSearchProvider();
const analyzer=analyzerSelection.provider, searchProvider=searchSelection.provider, messenger=new SimulatedMessagingProvider();
const wrap=(fn:any)=>(req:any,res:any,next:any)=>Promise.resolve(fn(req,res,next)).catch(next);
const auth=(req:any,_:any,next:any)=>req.session.userId?next():next(Object.assign(new Error("Authentication required"),{status:401}));
const admin=(req:any,_:any,next:any)=>req.session.role==="ADMIN"?next():next(Object.assign(new Error("Administrator access required"),{status:403}));
const audit=(userId:string|undefined,action:string,details:string,leadId?:string)=>prisma.auditLog.create({data:{userId,action,details,leadId}});
const parseJson=(s:string|null|undefined)=>{try{return JSON.parse(s||"[]")}catch{return[]}};
const cleanLead=(l:any)=>({...l,detectedSkills:parseJson(l.detectedSkills),riskFlags:parseJson(l.riskFlags)});
const transition=async(lead:any,to:any,userId?:string,details="")=>{assertTransition(lead.status,to);const updated=await prisma.lead.update({where:{id:lead.id},data:{status:to,reviewedAt:["APPROVED","REJECTED","DUPLICATE"].includes(to)?new Date():undefined,contactedAt:to==="CONTACTED"?new Date():undefined}});await audit(userId,`LEAD_${to}`,details||`${lead.status} to ${to}`,lead.id);return updated};
const authCookie="amh.auth";
const cookieOptions={httpOnly:true,sameSite:"lax" as const,secure:process.env.NODE_ENV==="production",maxAge:8*3600000,path:"/"};
const signSession=(session:{userId:string;role:"ADMIN"|"RECRUITER"})=>{const payload=Buffer.from(JSON.stringify({...session,exp:Date.now()+cookieOptions.maxAge})).toString("base64url");const signature=crypto.createHmac("sha256",process.env.SESSION_SECRET||"local-development-secret-change-this").update(payload).digest("base64url");return `${payload}.${signature}`};
const readSession=(token:string|undefined)=>{try{if(!token)return{};const [payload,signature]=token.split(".");const expected=crypto.createHmac("sha256",process.env.SESSION_SECRET||"local-development-secret-change-this").update(payload).digest("base64url");if(!signature||signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return{};const value=JSON.parse(Buffer.from(payload,"base64url").toString());if(value.exp<Date.now()||!value.userId||!["ADMIN","RECRUITER"].includes(value.role))return{};return {userId:value.userId,role:value.role}}catch{return{}}};
const processSearchRun=async(runId:string,input:any,userId:string)=>{
 try{
  const results=await searchProvider.search(input);
  let rawAnalyses;
  try{const providerWork=analyzer.analyzeBatch?analyzer.analyzeBatch(results):Promise.all(results.map(result=>analyzer.analyze(result)));rawAnalyses=await Promise.race([providerWork,new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error("Groq classification exceeded 20 seconds")),20_000))])}
  catch(error){const fallback=new MockAnalyzerProvider();rawAnalyses=await Promise.all(results.map(result=>fallback.analyze(result)));await audit(userId,"ANALYZER_FALLBACK",error instanceof Error?error.message:"Groq unavailable")}
  const analyses=rawAnalyses.map((analysis,index)=>enforceApplicantIntent(results[index],analysis));
  let qualified=0;
  for(const [index,r] of results.entries()){
   const a=analyses[index];
   if(!(a.classification==="ASPIRING_HELPER"&&a.explicitJobIntent&&matchesSelectedCountry(input,a)))continue;
   qualified++;
   const existing=await prisma.lead.findFirst({where:{OR:[{sourcePostExcerpt:{contains:r.text.slice(0,50)}},{publicDisplayName:r.name}]}});
   await prisma.lead.upsert({where:{sourceUrl:r.url},update:{classification:a.classification,explicitJobIntent:a.explicitJobIntent,confidenceScore:a.confidenceScore,aiSummary:a.summary,detectedCountry:a.country,detectedDestination:a.destination,detectedExperience:a.experience,detectedSkills:JSON.stringify(a.skills),detectedLanguage:a.detectedLanguage,searchRunId:runId},create:{publicDisplayName:r.name,sourceName:r.source,sourceUrl:r.url,sourcePostTitle:r.title,sourcePostExcerpt:r.text,sourcePublishedAt:r.publishedAt,detectedCountry:a.country,detectedDestination:a.destination,detectedExperience:a.experience,detectedSkills:JSON.stringify(a.skills),detectedLanguage:a.detectedLanguage,classification:a.classification,explicitJobIntent:a.explicitJobIntent,confidenceScore:a.confidenceScore,aiSummary:a.summary,riskFlags:JSON.stringify(existing?[...a.riskFlags,`Possible duplicate of ${existing.id}`]:a.riskFlags),possibleDuplicateId:existing?.id,registrationToken:crypto.randomBytes(24).toString("hex"),searchRunId:runId,assignedRecruiterId:userId,status:"PENDING_REVIEW"}});
  }
  await prisma.searchRun.update({where:{id:runId},data:{status:"COMPLETED",resultsFound:results.length,qualifiedResults:qualified,finishedAt:new Date()}});
  await audit(userId,"SEARCH_RUN_COMPLETED",`${results.length} ${searchSelection.name} results; ${qualified} qualified`);
 }catch(error){
  const message=error instanceof Error?error.message:"Search failed";
  await prisma.searchRun.update({where:{id:runId},data:{status:"FAILED",error:message,finishedAt:new Date()}});
  await audit(userId,"SEARCH_RUN_FAILED",message);
 }
};

export function createApp(){
 const app=express(); app.set("trust proxy",1); app.use(helmet({contentSecurityPolicy:false})); app.use(cors({origin:process.env.APP_ORIGIN||"http://localhost:5173",credentials:true}));
 app.use(express.json({limit:"100kb"})); app.use(cookieParser()); app.use((req:any,_res,next)=>{req.session=readSession(req.cookies?.[authCookie]);next()});
 const loginLimiter=rateLimit({
  windowMs:60000,
  limit:20,
  standardHeaders:"draft-8",
  legacyHeaders:false,
  handler:(_req,res)=>res.status(429).json({error:"Too many authentication requests. Please wait one minute and try again."})
 });
 app.post("/api/auth/login",loginLimiter,wrap(async(req:any,res:any)=>{const body=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);const u=await prisma.user.findUnique({where:{email:body.email.toLowerCase()}});if(!u||!await bcrypt.compare(body.password,u.passwordHash)) throw Object.assign(new Error("Invalid email or password"),{status:401});req.session={userId:u.id,role:u.role};res.cookie(authCookie,signSession(req.session),cookieOptions);await audit(u.id,"LOGIN","Successful login");res.json({id:u.id,name:u.name,email:u.email,role:u.role})}));
 app.post("/api/auth/logout",auth,(_req:any,res:any)=>{res.clearCookie(authCookie,{...cookieOptions,maxAge:undefined});res.status(204).end()});
 app.get("/api/auth/me",auth,wrap(async(req:any,res:any)=>res.json(await prisma.user.findUnique({where:{id:req.session.userId},select:{id:true,name:true,email:true,role:true}}))));

 const searchSchema=z.object({country:z.string().min(2),region:z.string().optional(),platform:z.enum(["All public sources","General Web","Facebook","Instagram","TikTok","LinkedIn","Reddit","Indeed","Job Boards"]).optional(),destination:z.string(),position:z.string(),language:z.string(),dateRange:z.string()});
 app.post("/api/search-runs",auth,wrap(async(req:any,res:any)=>{const input=searchSchema.parse(req.body);const queries=generateSearchQueries(input);const run=await prisma.searchRun.create({data:{country:input.country,destination:input.destination,position:input.position,language:input.language,dateRange:input.dateRange,generatedQueries:JSON.stringify(queries),createdById:req.session.userId,status:"RUNNING"}});void processSearchRun(run.id,input,req.session.userId);res.status(202).json({...run,generatedQueries:queries})}));
 app.get("/api/search-runs",auth,wrap(async(_:any,res:any)=>res.json(await prisma.searchRun.findMany({orderBy:{createdAt:"desc"},take:25,include:{createdBy:{select:{name:true}}}}))));
 app.get("/api/search-runs/:id",auth,wrap(async(req:any,res:any)=>{const r=await prisma.searchRun.findUnique({where:{id:req.params.id}});if(!r)throw Object.assign(new Error("Search run not found"),{status:404});const leads=await prisma.lead.findMany({where:{searchRunId:r.id,classification:"ASPIRING_HELPER",explicitJobIntent:true,...(r.country==="All selected countries"?{detectedCountry:{in:["Philippines","Indonesia","Myanmar","India","Nepal","Sri Lanka"]}}:{detectedCountry:r.country})}});res.json({...r,generatedQueries:parseJson(r.generatedQueries),leads:leads.map(cleanLead)})}));
 app.get("/api/leads",auth,wrap(async(req:any,res:any)=>{const where:any={classification:"ASPIRING_HELPER",explicitJobIntent:true};if(req.query.status)where.status=req.query.status;if(req.query.country)where.detectedCountry=req.query.country;if(req.query.q)where.OR=[{publicDisplayName:{contains:req.query.q}},{sourcePostExcerpt:{contains:req.query.q}}];const leads=await prisma.lead.findMany({where,orderBy:{discoveredAt:"desc"},include:{assignedRecruiter:{select:{id:true,name:true}},outreachMessages:{orderBy:{createdAt:"desc"},take:1}}});res.json(leads.map(cleanLead))}));
 app.get("/api/leads/:id",auth,wrap(async(req:any,res:any)=>{const l=await prisma.lead.findUnique({where:{id:req.params.id},include:{assignedRecruiter:{select:{id:true,name:true}},outreachMessages:true,screeningSessions:{include:{answers:true}},application:true,auditLogs:{orderBy:{createdAt:"asc"}}}});if(!l)throw Object.assign(new Error("Lead not found"),{status:404});res.json(cleanLead(l))}));
 app.patch("/api/leads/:id",auth,wrap(async(req:any,res:any)=>{const b=z.object({internalNote:z.string().max(2000).optional(),status:z.enum(["ARCHIVED"]).optional()}).parse(req.body);const l=await prisma.lead.findUniqueOrThrow({where:{id:req.params.id}});if(b.status)await transition(l,b.status,req.session.userId);const u=await prisma.lead.update({where:{id:l.id},data:{internalNote:b.internalNote}});await audit(req.session.userId,"LEAD_UPDATED","Internal lead details updated",l.id);res.json(cleanLead(u))}));
 app.delete("/api/leads/:id",auth,admin,wrap(async(req:any,res:any)=>{const lead=await prisma.lead.findUniqueOrThrow({where:{id:req.params.id},select:{id:true,publicDisplayName:true}});await prisma.$transaction([prisma.auditLog.deleteMany({where:{leadId:lead.id}}),prisma.lead.delete({where:{id:lead.id}})]);await audit(req.session.userId,"LEAD_DELETED",`Deleted lead: ${lead.publicDisplayName}`);res.status(204).end()}));
 app.post("/api/leads/:id/analyze",auth,wrap(async(req:any,res:any)=>{const l=await prisma.lead.findUniqueOrThrow({where:{id:req.params.id}});const a=await analyzer.analyze({name:l.publicDisplayName,title:l.sourcePostTitle,text:l.sourcePostExcerpt,url:l.sourceUrl,source:l.sourceName,publishedAt:l.sourcePublishedAt});res.json(a)}));
 for(const [path,to] of [["approve","APPROVED"],["reject","REJECTED"],["mark-duplicate","DUPLICATE"]] as const)app.post(`/api/leads/:id/${path}`,auth,wrap(async(req:any,res:any)=>{const l=await prisma.lead.findUniqueOrThrow({where:{id:req.params.id}});res.json(cleanLead(await transition(l,to,req.session.userId,req.body?.reason)))}));
 app.post("/api/leads/:id/keep-separate",auth,wrap(async(req:any,res:any)=>{const l=await prisma.lead.update({where:{id:req.params.id},data:{possibleDuplicateId:null,riskFlags:"[]"}});await audit(req.session.userId,"DUPLICATE_DISMISSED","Kept as separate lead",l.id);res.json(cleanLead(l))}));
 app.post("/api/leads/:id/assign",auth,wrap(async(req:any,res:any)=>{const b=z.object({recruiterId:z.string()}).parse(req.body);res.json(await prisma.lead.update({where:{id:req.params.id},data:{assignedRecruiterId:b.recruiterId}}))}));

 app.post("/api/leads/:id/outreach/generate",auth,wrap(async(req:any,res:any)=>{let l=await prisma.lead.findUniqueOrThrow({where:{id:req.params.id}});if(l.doNotContact)throw Object.assign(new Error("Lead is marked do not contact"),{status:403});if(l.status==="APPROVED")l=await transition(l,"CONTACT_READY",req.session.userId);if(l.status!=="CONTACT_READY")throw Object.assign(new Error("Lead must be approved before outreach"),{status:409});const messageText=`Hello, ${l.publicDisplayName}. We saw your public post saying that you are looking for domestic-helper work${l.detectedDestination?` in ${l.detectedDestination}`:""}. We are AT THE AGENCY, formerly RINZIN. Would you like information about our application process? Reply YES if interested or NO if you do not want further messages.`;const m=await prisma.outreachMessage.create({data:{leadId:l.id,messageText}});await audit(req.session.userId,"OUTREACH_GENERATED","Draft generated",l.id);res.status(201).json(m)}));
 app.patch("/api/outreach/:id",auth,wrap(async(req:any,res:any)=>{const b=z.object({messageText:z.string().min(20).max(2000)}).parse(req.body);const m=await prisma.outreachMessage.findUniqueOrThrow({where:{id:req.params.id},include:{lead:true}});if(m.lead.doNotContact)throw Object.assign(new Error("Do-not-contact is enforced"),{status:403});res.json(await prisma.outreachMessage.update({where:{id:m.id},data:{messageText:b.messageText,approved:false,version:{increment:1}}}))}));
 app.post("/api/outreach/:id/approve",auth,wrap(async(req:any,res:any)=>{const m=await prisma.outreachMessage.findUniqueOrThrow({where:{id:req.params.id},include:{lead:true}});if(m.lead.doNotContact)throw Object.assign(new Error("Do-not-contact is enforced"),{status:403});res.json(await prisma.outreachMessage.update({where:{id:m.id},data:{approved:true,approvedBy:req.session.userId}}))}));
 app.post("/api/outreach/:id/simulate-send",auth,wrap(async(req:any,res:any)=>{const m=await prisma.outreachMessage.findUniqueOrThrow({where:{id:req.params.id},include:{lead:true}});if(!m.approved)throw Object.assign(new Error("Message requires human approval"),{status:409});if(m.lead.doNotContact)throw Object.assign(new Error("Do-not-contact is enforced"),{status:403});await messenger.send(m.messageText);await transition(m.lead,"CONTACTED",req.session.userId);res.json({sent:true})}));
 app.post("/api/outreach/:id/simulate-response",auth,wrap(async(req:any,res:any)=>{const b=z.object({response:z.enum(["YES","NO","STOP","NO_RESPONSE"])}).parse(req.body);const m=await prisma.outreachMessage.findUniqueOrThrow({where:{id:req.params.id},include:{lead:true}});if(m.lead.status!=="CONTACTED")throw Object.assign(new Error("Lead must be contacted first"),{status:409});const to={YES:"INTERESTED",NO:"NOT_INTERESTED",STOP:"DO_NOT_CONTACT",NO_RESPONSE:"NO_RESPONSE"}[b.response];const l=await transition(m.lead,to,req.session.userId);await prisma.outreachMessage.update({where:{id:m.id},data:{simulatedResponse:b.response}});const data:any={consentToContinue:b.response==="YES",doNotContact:b.response==="STOP"};if(b.response==="YES")data.registrationToken=crypto.randomBytes(24).toString("hex");await prisma.lead.update({where:{id:l.id},data});res.json({...l,...data})}));

 app.get("/api/candidate/:token/screening",wrap(async(req:any,res:any)=>{const l=await prisma.lead.findUnique({where:{registrationToken:req.params.token},include:{screeningSessions:{orderBy:{createdAt:"desc"},take:1,include:{answers:true}}}});if(!l)throw Object.assign(new Error("Invalid candidate link"),{status:404});if(!l.consentToContinue||l.doNotContact)throw Object.assign(new Error("Screening is unavailable without consent"),{status:403});let s=l.screeningSessions[0];if(!s){if(l.status==="INTERESTED")await transition(l,"SCREENING",undefined);s=await prisma.screeningSession.create({data:{leadId:l.id},include:{answers:true}})}res.json({lead:{publicDisplayName:l.publicDisplayName,status:l.status},session:s,question:s.completed?null:screeningQuestions[s.currentQuestion]})}));
 app.post("/api/candidate/:token/screening/answer",wrap(async(req:any,res:any)=>{const b=z.object({answer:z.string().min(1).max(1000)}).parse(req.body);const l=await prisma.lead.findUnique({where:{registrationToken:req.params.token},include:{screeningSessions:{orderBy:{createdAt:"desc"},take:1}}});if(!l||!l.consentToContinue||l.doNotContact)throw Object.assign(new Error("Screening is unavailable"),{status:403});const s=l.screeningSessions[0];if(!s||s.pausedForHuman||s.completed)throw Object.assign(new Error("Screening is not active"),{status:409});const q=screeningQuestions[s.currentQuestion];await prisma.screeningAnswer.create({data:{screeningSessionId:s.id,questionKey:q[0],questionText:q[1],answerText:b.answer}});const done=s.currentQuestion+1>=screeningQuestions.length;const updated=await prisma.screeningSession.update({where:{id:s.id},data:{currentQuestion:{increment:1},completed:done,completedAt:done?new Date():undefined,summary:done?"Candidate completed all prototype screening questions. Recruiter review is required.":undefined,recommendedNextStep:done?"Invite candidate to complete the test application.":undefined}});await audit(undefined,"SCREENING_ANSWERED",q[0],l.id);res.json({session:updated,question:done?null:screeningQuestions[updated.currentQuestion]})}));
 app.post("/api/candidate/:token/request-human",wrap(async(req:any,res:any)=>{const l=await prisma.lead.findUniqueOrThrow({where:{registrationToken:req.params.token},include:{screeningSessions:{orderBy:{createdAt:"desc"},take:1}}});const s=l.screeningSessions[0];if(s)await prisma.screeningSession.update({where:{id:s.id},data:{pausedForHuman:true,recommendedNextStep:"Human recruiter requested"}});await audit(undefined,"HUMAN_RECRUITER_REQUESTED","Candidate paused AI screening",l.id);res.json({paused:true})}));
 const applicationSchema=z.object({fullName:z.string().min(2),country:z.string().min(2),contactMethod:z.string(),contactValue:z.string().min(3),experience:z.string().min(2),overseasExperience:z.string().min(2),skills:z.string().min(2),availability:z.string().min(2),preferredLanguage:z.string(),consentAccepted:z.literal(true)});
 app.get("/api/candidate/:token/application",wrap(async(req:any,res:any)=>{const l=await prisma.lead.findUnique({where:{registrationToken:req.params.token},include:{application:true}});if(!l||!["INTERESTED","SCREENING"].includes(l.status)||!l.consentToContinue||l.doNotContact)throw Object.assign(new Error("Application is unavailable"),{status:403});res.json({lead:{publicDisplayName:l.publicDisplayName},application:l.application})}));
 app.post("/api/candidate/:token/application",wrap(async(req:any,res:any)=>{const b=applicationSchema.parse(req.body);const l=await prisma.lead.findUnique({where:{registrationToken:req.params.token}});if(!l||!["INTERESTED","SCREENING"].includes(l.status)||!l.consentToContinue||l.doNotContact)throw Object.assign(new Error("Application is unavailable"),{status:403});const a=await prisma.testApplication.create({data:{...b,leadId:l.id}});await transition(l,"APPLICATION_SUBMITTED",undefined);await audit(undefined,"APPLICATION_SUBMITTED","Prototype application submitted",l.id);res.status(201).json(a)}));
 app.get("/api/applications",auth,wrap(async(_:any,res:any)=>res.json(await prisma.testApplication.findMany({orderBy:{submittedAt:"desc"},include:{lead:{select:{publicDisplayName:true,status:true}}}}))));
 app.get("/api/applications/:id",auth,wrap(async(req:any,res:any)=>res.json(await prisma.testApplication.findUniqueOrThrow({where:{id:req.params.id},include:{lead:{include:{screeningSessions:{include:{answers:true}}}}}}))));
 app.get("/api/audit-logs",auth,admin,wrap(async(_:any,res:any)=>res.json(await prisma.auditLog.findMany({orderBy:{createdAt:"desc"},take:200,include:{user:{select:{name:true}},lead:{select:{publicDisplayName:true}}}}))));
 app.get("/api/users",auth,admin,wrap(async(_:any,res:any)=>res.json(await prisma.user.findMany({select:{id:true,name:true,email:true,role:true,createdAt:true}}))));
 app.post("/api/users",auth,admin,wrap(async(req:any,res:any)=>{const b=z.object({name:z.string().trim().min(2).max(100),email:z.string().trim().email(),password:z.string().min(8).max(128),role:z.enum(["ADMIN","RECRUITER"])}).parse(req.body);const email=b.email.toLowerCase();if(await prisma.user.findUnique({where:{email},select:{id:true}}))throw Object.assign(new Error("A user with this email already exists"),{status:409});const created=await prisma.user.create({data:{name:b.name,email,passwordHash:await bcrypt.hash(b.password,12),role:b.role},select:{id:true,name:true,email:true,role:true,createdAt:true}});await audit(req.session.userId,"USER_CREATED",`Created ${created.role.toLowerCase()} account: ${created.email}`);res.status(201).json(created)}));
 app.patch("/api/users/:id",auth,admin,wrap(async(req:any,res:any)=>{const b=z.object({name:z.string().min(2).optional(),role:z.enum(["ADMIN","RECRUITER"]).optional()}).parse(req.body);res.json(await prisma.user.update({where:{id:req.params.id},data:b}))}));
 app.delete("/api/users/:id",auth,admin,wrap(async(req:any,res:any)=>{const target=await prisma.user.findUnique({where:{id:req.params.id},select:{id:true,name:true,email:true,role:true}});if(!target)throw Object.assign(new Error("User not found"),{status:404});const deletingSelf=target.id===req.session.userId;const adminCount=await prisma.user.count({where:{role:"ADMIN"}});if(target.role==="ADMIN"&&adminCount<=1)throw Object.assign(new Error("Add another administrator before deleting this account"),{status:409});const replacement=deletingSelf?await prisma.user.findFirst({where:{role:"ADMIN",id:{not:target.id}},select:{id:true}}):{id:req.session.userId};if(!replacement)throw Object.assign(new Error("Add another administrator before deleting this account"),{status:409});await prisma.$transaction([prisma.searchRun.updateMany({where:{createdById:target.id},data:{createdById:replacement.id}}),prisma.lead.updateMany({where:{assignedRecruiterId:target.id},data:{assignedRecruiterId:replacement.id}}),prisma.auditLog.updateMany({where:{userId:target.id},data:{userId:null}}),prisma.user.delete({where:{id:target.id}}),prisma.auditLog.create({data:{userId:deletingSelf?null:req.session.userId,action:"USER_DELETED",details:`Deleted ${target.role.toLowerCase()} account: ${target.email}`}})]);if(deletingSelf)return req.session.destroy((error:any)=>{if(error)return res.status(500).json({error:"Account deleted, but the session could not be closed"});res.clearCookie("amh.sid",{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production"});res.status(204).end()});res.status(204).end()}));
 app.get("/api/dashboard",auth,wrap(async(_:any,res:any)=>{const [leadCounts,searches,apps,logs]=await Promise.all([prisma.lead.groupBy({by:["status"],_count:{_all:true}}),prisma.searchRun.findMany({take:5,orderBy:{createdAt:"desc"}}),prisma.testApplication.findMany({take:5,orderBy:{submittedAt:"desc"},include:{lead:true}}),prisma.auditLog.findMany({take:8,orderBy:{createdAt:"desc"}})]);const counts=Object.fromEntries(leadCounts.map(row=>[row.status,row._count._all]));const total=leadCounts.reduce((sum,row)=>sum+row._count._all,0);res.json({total,counts,searches,applications:apps,logs})}));
 app.get("/api/settings/providers",auth,(_:any,res:any)=>res.json({search:searchSelection.name,searchConfigured:searchSelection.configured,analyzer:analyzerSelection.name,messaging:"simulated",model:analyzerSelection.name==="groq"?process.env.GROQ_MODEL||"openai/gpt-oss-20b":null}));
 app.use((err:any,_req:any,res:any,_next:any)=>{
  if(err instanceof z.ZodError)return res.status(400).json({error:"Validation failed",issues:err.issues});
  const status=Number(err.status)||500;
  // Authentication, authorization, conflicts, and other expected client errors
  // are normal API responses and should not produce alarming stack traces.
  if(status>=500)console.error(err);
  res.status(status).json({error:status<500?err.message:"Unexpected server error"});
 }); return app;
}
